spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CityGuide
    username: root
    password: root-password
  jpa.hibernate:
    naming-strategy: PhysicalNamingStrategyStandardImpl
    ddl-auto: update